version: 1.0.{build}
branches:
  only:
  - master
image: Ubuntu1804
configuration: Release
build:
  project: CSharpRecordsAnalyzer.sln
  verbosity: minimal
test_script:
- sh: dotnet test --test-adapter-path:. --logger:Appveyor
artifacts:
- path: src/CSharpRecordsAnalyzer/bin/Release/*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: hbDqibGxfpPIaFVOiZOprzr5Kvrui9Pmq0I3XkncYTew4aruZAVUKTbA+Ch1mfLP
  skip_symbols: true
  on:
    branch: master